### ISSUE TITLE
It seems not work now. please check the debug imformantion.

### ISSUE THREAD

**Issue by llity** [stroebjo/alfred-recent#2]
[09:26:27.863] Logging Started...
[09:26:29.799] Recently used files by an App[Script Filter] Queuing argument ''
[09:26:29.880] Recently used files by an App[Script Filter] Script with argv '(null)' finished
[09:26:29.882] ERROR: Recently used files by an App[Script Filter] Code 1: Traceback (most recent call last):
  File "./recent.py", line 59, in <module>
    items = json.loads(stdout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by stroebjo** [comment]
Sorry, this is a known issue with macOS > 10.12.x. Apple changed something in the plist format and I haven't gotten around to fixing it (see #1).
